/**
 * MSW handlers covering the happy-path of every endpoint defined in
 * `src/endpoints/`. Apps import these in their Vitest or Playwright
 * setup to mock the backend without spinning up a real server.
 *
 * Each handler returns a deterministic payload generated by the
 * factories. Override behavior in individual tests with `server.use(...)`.
 */

import { http, HttpResponse } from "msw";

import {
  makeAuthTokens,
  makeBaseUser,
  makeCustomer,
  makeDriver,
  makeOrder,
  makeRestaurant,
} from "./factories";

const success = <T>(data: T, message?: string) =>
  HttpResponse.json({ success: true, data, ...(message ? { message } : {}) });

const paginated = <T>(items: T[], page = 1, limit = 20) =>
  HttpResponse.json({
    success: true,
    data: items,
    pagination: {
      page,
      limit,
      total: items.length,
      totalPages: Math.max(1, Math.ceil(items.length / limit)),
      hasNextPage: false,
      hasPrevPage: page > 1,
    },
  });

export const createDefaultHandlers = (baseURL = "http://localhost:5000") => [
  // ── auth ────────────────────────────────────────────────────────────────
  http.post(`${baseURL}/api/v1/auth/register`, () =>
    success({ user: makeBaseUser({ role: "customer" }), message: "OTP sent" }),
  ),
  http.post(`${baseURL}/api/v1/auth/verify-email`, () =>
    success({ user: makeBaseUser(), tokens: makeAuthTokens() }),
  ),
  http.post(`${baseURL}/api/v1/auth/resend-otp`, () => success({ message: "OTP resent" })),
  http.post(`${baseURL}/api/v1/auth/login`, () =>
    success({ user: makeBaseUser(), tokens: makeAuthTokens() }),
  ),
  http.post(`${baseURL}/api/v1/auth/google`, () =>
    success({ user: makeBaseUser(), tokens: makeAuthTokens() }),
  ),
  http.post(`${baseURL}/api/v1/auth/forgot-password`, () => success({ message: "OTP sent" })),
  http.post(`${baseURL}/api/v1/auth/reset-password`, () => success({ message: "Password reset" })),
  http.post(`${baseURL}/api/v1/auth/change-password`, () =>
    success({ message: "Password changed" }),
  ),
  http.post(`${baseURL}/api/v1/auth/refresh-token`, () => success(makeAuthTokens())),
  http.post(`${baseURL}/api/v1/auth/update-fcm-token`, () => success({ message: "Updated" })),
  http.post(`${baseURL}/api/v1/auth/logout`, () => success({ message: "Logged out" })),
  http.get(`${baseURL}/api/v1/auth/me`, () => success(makeBaseUser())),

  // ── customer ────────────────────────────────────────────────────────────
  http.get(`${baseURL}/api/v1/customer/profile`, () => success(makeCustomer())),
  http.get(`${baseURL}/api/v1/customer/loyalty-points`, () =>
    success({ points: 50, tier: "silver" }),
  ),
  http.get(`${baseURL}/api/v1/customer/addresses`, () => success([])),
  http.get(`${baseURL}/api/v1/customer/addresses/default`, () => success(null)),
  http.post(`${baseURL}/api/v1/customer/addresses`, async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return success({ id: "addr_new", ...body });
  }),
  http.put(`${baseURL}/api/v1/customer/addresses/:id`, async ({ request, params }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return success({ id: params.id, ...body });
  }),
  http.delete(`${baseURL}/api/v1/customer/addresses/:id`, () => success({ message: "Deleted" })),
  http.patch(`${baseURL}/api/v1/customer/addresses/:id/default`, ({ params }) =>
    success({ id: params.id, isDefault: true }),
  ),
  http.get(`${baseURL}/api/v1/customer/favorites`, () => success([])),
  http.post(`${baseURL}/api/v1/customer/favorites/:restaurantId`, () =>
    success({ message: "Added" }),
  ),
  http.delete(`${baseURL}/api/v1/customer/favorites/:restaurantId`, () =>
    success({ message: "Removed" }),
  ),
  http.get(`${baseURL}/api/v1/customer/favorites/:restaurantId/check`, () =>
    success({ isFavorite: false }),
  ),

  // ── restaurants ─────────────────────────────────────────────────────────
  http.get(`${baseURL}/api/v1/restaurants/featured`, () => success([makeRestaurant()])),
  http.get(`${baseURL}/api/v1/restaurants/nearby`, () => success([makeRestaurant()])),
  http.get(`${baseURL}/api/v1/restaurants`, () => paginated([makeRestaurant(), makeRestaurant()])),
  http.get(`${baseURL}/api/v1/restaurants/:slug/menu`, () =>
    success({ categories: [], items: [] }),
  ),
  http.get(`${baseURL}/api/v1/restaurants/:slug`, () => success(makeRestaurant())),

  // ── orders (customer) ───────────────────────────────────────────────────
  http.post(`${baseURL}/api/v1/orders`, () => success(makeOrder())),
  http.get(`${baseURL}/api/v1/orders`, () => paginated([makeOrder()])),
  http.get(`${baseURL}/api/v1/orders/:id`, () => success(makeOrder())),
  http.put(`${baseURL}/api/v1/orders/:id/cancel`, () =>
    success(makeOrder({ status: "cancelled" })),
  ),
  http.post(`${baseURL}/api/v1/orders/:id/rate`, () => success(makeOrder())),
  http.post(`${baseURL}/api/v1/orders/:id/reorder`, () => success(makeOrder())),

  // ── driver ──────────────────────────────────────────────────────────────
  http.get(`${baseURL}/api/v1/driver/profile`, () => success(makeDriver())),
  http.patch(`${baseURL}/api/v1/driver/profile`, () => success(makeDriver())),
  http.put(`${baseURL}/api/v1/driver/avatar`, () => success(makeDriver())),
  http.put(`${baseURL}/api/v1/driver/location`, () => success({ message: "Updated" })),
  http.put(`${baseURL}/api/v1/driver/online`, () => success(makeDriver({ isOnline: true }))),
  http.put(`${baseURL}/api/v1/driver/availability`, () =>
    success(makeDriver({ isAvailable: true })),
  ),
  http.get(`${baseURL}/api/v1/driver/stats`, () =>
    success({
      totalDeliveries: 0,
      totalEarnings: 0,
      rating: 0,
      totalReviews: 0,
      walletBalance: 0,
      pendingPayouts: 0,
    }),
  ),
  http.put(`${baseURL}/api/v1/driver/documents`, () => success(makeDriver())),
  http.get(`${baseURL}/api/v1/driver/orders/available`, () =>
    success([makeOrder({ status: "ready" })]),
  ),
  http.get(`${baseURL}/api/v1/driver/orders`, () => paginated([makeOrder()])),
  http.put(`${baseURL}/api/v1/driver/orders/:id/accept`, () =>
    success(makeOrder({ status: "picked_up" })),
  ),
  http.put(`${baseURL}/api/v1/driver/orders/:id/reject`, () => success({ message: "Rejected" })),
  http.put(`${baseURL}/api/v1/driver/orders/:id/pickup`, () =>
    success(makeOrder({ status: "picked_up" })),
  ),
  http.put(`${baseURL}/api/v1/driver/orders/:id/on-the-way`, () =>
    success(makeOrder({ status: "on_the_way" })),
  ),
  http.put(`${baseURL}/api/v1/driver/orders/:id/delivered`, () =>
    success(makeOrder({ status: "delivered" })),
  ),

  // ── coupons ─────────────────────────────────────────────────────────────
  http.get(`${baseURL}/api/v1/coupons`, () => success([])),
  http.post(`${baseURL}/api/v1/coupons/validate`, () =>
    HttpResponse.json({
      success: true,
      data: { isValid: false, discount: 0, reason: "not_found", coupon: null },
    }),
  ),

  // ── reviews ─────────────────────────────────────────────────────────────
  http.get(`${baseURL}/api/v1/restaurants/:id/reviews`, () => paginated([])),
  http.get(`${baseURL}/api/v1/customer/reviews`, () => paginated([])),
  http.post(`${baseURL}/api/v1/reviews`, () =>
    success({
      id: "rev_test",
      orderId: "ord_test",
      customerId: "cust_test",
      type: "restaurant" as const,
      rating: 5,
      images: [],
      isVisible: true,
      createdAt: "2026-05-13T00:00:00.000Z",
      updatedAt: "2026-05-13T00:00:00.000Z",
    }),
  ),

  // ── notifications ───────────────────────────────────────────────────────
  http.get(`${baseURL}/api/v1/notifications`, () => paginated([])),
  http.get(`${baseURL}/api/v1/notifications/unread-count`, () => success({ count: 0 })),
  http.put(`${baseURL}/api/v1/notifications/:id/read`, () => success({ message: "Read" })),
  http.put(`${baseURL}/api/v1/notifications/read-all`, () => success({ message: "All read" })),
  http.delete(`${baseURL}/api/v1/notifications/:id`, () => success({ message: "Removed" })),
  http.post(`${baseURL}/api/v1/notifications/push/subscribe`, () =>
    success({ message: "Subscribed" }),
  ),
  http.post(`${baseURL}/api/v1/notifications/push/unsubscribe`, () =>
    success({ message: "Unsubscribed" }),
  ),

  // ── uploads ─────────────────────────────────────────────────────────────
  http.post(`${baseURL}/api/v1/upload/:kind`, () =>
    success({ url: "https://cdn.bagour.test/img.jpg", publicId: "bagour_test" }),
  ),
  http.delete(`${baseURL}/api/v1/upload/:publicId`, () => success({ message: "Deleted" })),
];
